import type { ProjectState } from '@pc/store/types.js'
import { generateTeamReportCsv } from '@pc/engine/governance.js'
import { teamReportTemplates } from '@pc/data/governance.js'
import { sumBac, sumCostSheetMetric } from '@pc/engine/costAggregation.js'

export interface ClosePackFile {
  name: string
  mimeType: string
  content: string
}

export interface ClosePackBundle {
  projectId: string
  projectName: string
  generatedAt: string
  files: ClosePackFile[]
}

/** Leadership-trusted close pack — server-generated, control-account totals. */
export function generateClosePack(state: ProjectState, generatedBy: string): ClosePackBundle {
  const costSummary = teamReportTemplates.find((template) => template.template === 'cost_summary')
  const evmSnapshot = teamReportTemplates.find((template) => template.template === 'evm_snapshot')
  const changePipeline = teamReportTemplates.find((template) => template.template === 'change_pipeline')
  const auditActivity = teamReportTemplates.find((template) => template.template === 'audit_activity')
  const commitmentReport = teamReportTemplates.find((template) => template.template === 'commitment_report')
  const invoiceReport = teamReportTemplates.find((template) => template.template === 'invoice_status')
  const accrualReport = teamReportTemplates.find((template) => template.template === 'accrual_report')
  const contingencyReport = teamReportTemplates.find((template) => template.template === 'contingency_report')

  const files: ClosePackFile[] = []

  if (costSummary) {
    const report = generateTeamReportCsv(costSummary, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (evmSnapshot) {
    const report = generateTeamReportCsv(evmSnapshot, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (changePipeline) {
    const report = generateTeamReportCsv(changePipeline, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (auditActivity) {
    const report = generateTeamReportCsv(auditActivity, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (commitmentReport) {
    const report = generateTeamReportCsv(commitmentReport, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (invoiceReport) {
    const report = generateTeamReportCsv(invoiceReport, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (accrualReport) {
    const report = generateTeamReportCsv(accrualReport, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }
  if (contingencyReport) {
    const report = generateTeamReportCsv(contingencyReport, state, generatedBy)
    files.push({ name: report.name, mimeType: 'text/csv', content: report.content })
  }

  const executiveSummary = [
    `Executive Close Summary — ${state.meta.name}`,
    `Period: ${state.meta.baselineLabel}`,
    `Generated: ${new Date().toISOString()}`,
    `Generated by: ${generatedBy}`,
    '',
    `BAC (control accounts): ${sumBac(state.costSheetRows).toLocaleString()}`,
    `Actuals: ${sumCostSheetMetric(state.costSheetRows, 'actualsToDate').toLocaleString()}`,
    `EAC: ${sumCostSheetMetric(state.costSheetRows, 'eac').toLocaleString()}`,
    '',
    'Financial grain: control accounts only — no WBS parent/child double-count.',
    `Files in pack: ${files.map((file) => file.name).join(', ')}`,
  ].join('\n')

  files.unshift({
    name: '00-executive-summary.txt',
    mimeType: 'text/plain',
    content: executiveSummary,
  })

  return {
    projectId: state.meta.id,
    projectName: state.meta.name,
    generatedAt: new Date().toISOString(),
    files,
  }
}
